#############################################################################
# Makefile for building: ModernChat.app/Contents/MacOS/ModernChat
# Generated by qmake (3.1) (Qt 5.15.16)
# Project:  modern_chat.pro
# Template: app
# Command: /opt/homebrew/opt/qt@5/bin/qmake -o Makefile modern_chat.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.16_1/lib
QMAKE         = /opt/homebrew/opt/qt@5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/opt/qt@5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/opt/qt@5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ModernChat1.0.0
DISTDIR = /Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat/.tmp/ModernChat1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.16_1/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main_modern.cpp \
		modernChat.cpp \
		chatbubble.cpp moc_modernChat.cpp \
		moc_chatbubble.cpp
OBJECTS       = main_modern.o \
		modernChat.o \
		chatbubble.o \
		moc_modernChat.o \
		moc_chatbubble.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/lex.prf \
		modern_chat.pro modernChat.h \
		chatbubble.h main_modern.cpp \
		modernChat.cpp \
		chatbubble.cpp
QMAKE_TARGET  = ModernChat
DESTDIR       = 
TARGET        = ModernChat.app/Contents/MacOS/ModernChat

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat/modern_chat.pro


include /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

ModernChat.app/Contents/MacOS/ModernChat:  $(OBJECTS)  
	@test -d ModernChat.app/Contents/MacOS/ || mkdir -p ModernChat.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: modern_chat.pro /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/lex.prf \
		modern_chat.pro \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile modern_chat.pro
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/lex.prf:
modern_chat.pro:
/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile modern_chat.pro

qmake_all: FORCE

ModernChat.app/Contents/PkgInfo: 
	@test -d ModernChat.app/Contents || mkdir -p ModernChat.app/Contents
	@$(DEL_FILE) ModernChat.app/Contents/PkgInfo
	@echo "APPL????" > ModernChat.app/Contents/PkgInfo
ModernChat.app/Contents/Resources/empty.lproj: 
	@test -d ModernChat.app/Contents/Resources || mkdir -p ModernChat.app/Contents/Resources
	@touch ModernChat.app/Contents/Resources/empty.lproj
	
ModernChat.app/Contents/Info.plist: 
	@test -d ModernChat.app/Contents || mkdir -p ModernChat.app/Contents
	@$(DEL_FILE) ModernChat.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.demo.ModernChat,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.demo.ModernChat,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,ModernChat,g" -e "s,@LIBRARY@,ModernChat,g" -e "s,\$${EXECUTABLE_NAME},ModernChat,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang/Info.plist.app >ModernChat.app/Contents/Info.plist

all: Makefile \
		ModernChat.app/Contents/PkgInfo \
		ModernChat.app/Contents/Resources/empty.lproj \
		ModernChat.app/Contents/Info.plist ModernChat.app/Contents/MacOS/ModernChat

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents modernChat.h chatbubble.h $(DISTDIR)/
	$(COPY_FILE) --parents main_modern.cpp modernChat.cpp chatbubble.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ModernChat.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -mmacosx-version-min=10.14 -Wall -Wextra -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_modernChat.cpp moc_chatbubble.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_modernChat.cpp moc_chatbubble.cpp
moc_modernChat.cpp: modernChat.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QGroupBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpServer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QInputDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMenuBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QStatusBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qframe.h \
		chatbubble.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPaintEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qevent.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16_1/bin/moc $(DEFINES) --include /Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang -I/Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16_1/lib modernChat.h -o moc_modernChat.cpp

moc_chatbubble.cpp: chatbubble.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPaintEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdatetime.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16_1/bin/moc $(DEFINES) --include /Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16_1/mkspecs/macx-clang -I/Users/zhaoren/winfile/cpp-qt-homework/assignment2-chat -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16_1/lib chatbubble.h -o moc_chatbubble.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main_modern.o: main_modern.cpp /opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qapplication.h \
		modernChat.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QGroupBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpServer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QInputDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMenuBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QStatusBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qframe.h \
		chatbubble.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPaintEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_modern.o main_modern.cpp

modernChat.o: modernChat.cpp modernChat.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QGroupBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpServer \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QInputDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QMenuBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QStatusBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QStandardPaths \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qstandardpaths.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QScrollBar \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qframe.h \
		chatbubble.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPaintEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modernChat.o modernChat.cpp

chatbubble.o: chatbubble.cpp chatbubble.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPaintEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QPainterPath \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qpainterpath.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/QFontMetrics \
		/opt/homebrew/Cellar/qt@5/5.15.16_1/lib/QtGui.framework/Headers/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatbubble.o chatbubble.cpp

moc_modernChat.o: moc_modernChat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modernChat.o moc_modernChat.cpp

moc_chatbubble.o: moc_chatbubble.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatbubble.o moc_chatbubble.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

